"""Legal & Admin — replayable evaluation scenarios (see evals/legal.md).

Each test replays one realistic customer request through the agent's tools exactly as the
customer's AI would call them, and asserts on values verified BY HAND or with the independent
stdlib helpers below (they never import `hundred`). Scenario documents were written for this
eval (no third-party contract text) with planted issues; recall and precision are asserted.

Regulatory figures used (checked 2026-09-27):
- 2 CFR 200.1 MTDC / Equipment (awards on/after 2024-10-01): first $50,000 of each subaward,
  equipment >= $10,000 per unit; 2 CFR 200.414(f) de minimis up to 15%; 200.344(b) final
  reports within 120 days. Pre-2024 awards: $25,000 / $5,000 / 10%.
- Cal. Civ. Code 1798.140(d)(1): revenue > $25M as adjusted ($26,625,000 from 2025-01-01, CPPA),
  OR buys/sells/shares PI of 100,000+ consumers/households, OR >= 50% revenue from selling/sharing.
"""

from __future__ import annotations

import calendar
from datetime import date, timedelta

import pytest

from hundred import registry

# ── independent reference math (no `hundred` imports) ──────────────────────────


def add_months(d: date, months: int) -> date:
    y, m = divmod(d.month - 1 + months, 12)
    y += d.year
    return date(y, m + 1, min(d.day, calendar.monthrange(y, m + 1)[1]))


def last_day_of_term(start: date, months: int) -> date:
    """A 12-month term from 2026-10-31 runs through 2027-10-30 (the day before the anniversary)."""
    anniversary = add_months(start, months)
    return anniversary if anniversary.day != start.day else anniversary - timedelta(days=1)


def friday_before(d: date) -> date:
    return d - timedelta(days=d.weekday() - 4) if d.weekday() >= 5 else d


def call(slug: str, tool: str, **kwargs):
    out = registry.get(slug).get_tool(tool).call(kwargs)
    assert "not legal" in out.get("scope_note", "").lower(), f"{slug}.{tool} output lacks the not-legal-advice scope note"
    return out


def flags_of(out: dict) -> list[str]:
    return [f["flag"] for f in out["red_flags"]]


# ── scenario documents (written for this eval; planted issues listed next to each test) ──

SAAS_CONTRACT = """\nSOFTWARE SUBSCRIPTION AGREEMENT

This Software Subscription Agreement (the "Agreement") is entered into as of October 31, 2026 (the "Effective Date") between Stratus Ledger Systems, LLC, a Florida limited liability company ("Provider"), and Cascade Outdoor Supply, Inc., an Oregon corporation with its principal office in Portland, Oregon ("Customer").

1. DEFINITIONS

1.1 "Services" means Provider's hosted inventory and order-management platform, the related mobile applications, and the Documentation, as described in the Order Form.

1.2 "Customer Data" means data, files and records that Customer or its Users upload to or enter into the Services.

1.3 "Usage Data" means information generated by or derived from the operation of the Services, including configuration settings, performance metrics, transaction volumes, and statistical or analytical data derived from Customer Data.

1.4 "Order Form" means the ordering document signed by both parties that references this Agreement and states the Subscription Fees, user counts and modules purchased.

1.5 "Users" means Customer's employees and contractors authorized by Customer to access the Services.

2. ACCESS TO THE SERVICES

2.1 Subject to Customer's payment of all Fees, Provider grants Customer a non-exclusive, non-transferable right to access and use the Services during the Term solely for Customer's internal business operations.

2.2 Customer shall not (a) resell or sublicense the Services, (b) reverse engineer any part of the Services, or (c) use the Services to build a competing product.

2.3 Provider may modify the features and functionality of the Services from time to time, provided that such modifications do not materially reduce the core functionality of the Services during the then-current term.

3. FEES AND PAYMENT

3.1 Customer shall pay the subscription fees set out in the Order Form, currently four thousand dollars ($4,000) per month, billed annually in advance (the "Fees"). Invoices are payable within thirty (30) days of the invoice date.

3.2 Provider may change the Fees, or introduce new fees for existing features, at any time upon written notice to Customer, and the revised Fees shall apply from the date stated in the notice. Customer's continued use of the Services after that date constitutes acceptance of the revised Fees.

3.3 Overdue amounts bear interest at the lesser of 1.0% per month or the maximum rate permitted by law. Provider may suspend the Services if any undisputed amount is more than thirty (30) days overdue, after giving Customer ten (10) days' written notice.

3.4 Fees are exclusive of taxes. Customer is responsible for sales, use and similar taxes, other than taxes based on Provider's net income.

3.5 Promotional onboarding pricing, if stated in the Order Form, remains in effect through February 28, 2027.

4. TERM AND RENEWAL

4.1 This Agreement commences on the Effective Date and continues for an initial term of twelve (12) months (the "Initial Term").

4.2 Thereafter, this Agreement shall automatically renew for successive twelve (12) month renewal terms (each a "Renewal Term" and, together with the Initial Term, the "Term") unless either party gives written notice of non-renewal at least ninety (90) days prior to the end of the then-current term.

5. TERMINATION

5.1 Provider may terminate this Agreement for convenience at any time upon thirty (30) days' written notice to Customer.

5.2 Either party may terminate this Agreement if the other party materially breaches it and fails to cure the breach within thirty (30) days after receiving written notice describing the breach.

5.3 Fees paid or payable for the Initial Term or any Renewal Term are non-cancellable and non-refundable, and Customer shall have no right to terminate this Agreement prior to the end of the then-current term except as set out in Section 5.2.

5.4 Upon termination or expiration, Customer's right to access the Services ends. For thirty (30) days after termination, Provider will make Customer Data available for export in Provider's standard format, after which Provider may delete it.

6. DATA

6.1 Customer grants Provider a worldwide, perpetual, irrevocable, royalty-free license to use, copy, modify and create derivative works of Customer Data and Usage Data to provide, maintain and improve the Services and Provider's other products and services.

6.2 Provider owns all right, title and interest in and to the Services, Usage Data, and all aggregated or de-identified data derived from Customer Data, and all improvements to any of them.

6.3 Provider will implement reasonable administrative, physical and technical safeguards designed to protect Customer Data. To the extent Provider processes personal data on Customer's behalf, the parties will enter into Provider's standard data processing addendum.

6.4 Provider will notify Customer without undue delay after becoming aware of a security incident that results in unauthorized access to Customer Data.

7. CONFIDENTIALITY

7.1 "Confidential Information" means non-public information disclosed by one party to the other that is marked as confidential or that a reasonable person would understand to be confidential. Confidential Information does not include information that is or becomes publicly available through no fault of the receiving party, was known to the receiving party before disclosure, is independently developed, or is received from a third party without restriction.

7.2 Each party shall use the other party's Confidential Information only to perform under this Agreement and shall protect it using at least reasonable care. These obligations survive for three (3) years after termination of this Agreement.

8. SERVICE LEVELS

8.1 Provider will use commercially reasonable efforts to make the Services available 99.9% of the time in each calendar month, excluding scheduled maintenance announced at least forty-eight (48) hours in advance. If availability falls below 99.9% in a month, Customer will receive a service credit of 5% of that month's Fees for each full 1% below the target, up to 25% of the monthly Fees, provided Customer requests the credit within thirty (30) days after the end of the affected month.

9. WARRANTIES

9.1 Provider warrants that the Services will perform materially in accordance with the Documentation. If they do not, Provider will use commercially reasonable efforts to correct the non-conformity, and if it cannot do so within thirty (30) days, Customer may terminate the affected Order Form and receive a refund of prepaid Fees for the remainder of the term.

9.2 EXCEPT AS EXPRESSLY STATED IN THIS SECTION 9, PROVIDER DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

10. INDEMNIFICATION

10.1 Customer shall defend, indemnify and hold harmless Provider and its affiliates, officers and employees from and against any and all claims, losses, damages, liabilities, costs and expenses (including attorneys' fees) arising out of or relating to Customer Data, Customer's use of the Services, or any breach of this Agreement by Customer or its Users. Customer's obligations under this Section 10.1 are not subject to any limitation of liability in this Agreement.

10.2 Provider will defend Customer against any third-party claim alleging that the Services, as provided by Provider, infringe a United States patent or copyright, and will pay damages finally awarded against Customer in such a claim, subject to Section 11.

11. LIMITATION OF LIABILITY

11.1 IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR FOR LOST PROFITS OR REVENUES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

11.2 PROVIDER'S AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT SHALL NOT EXCEED THE FEES PAID BY CUSTOMER IN THE ONE (1) MONTH PRECEDING THE EVENT GIVING RISE TO THE CLAIM.

12. INSURANCE

12.1 Provider will maintain commercial general liability insurance and cyber liability insurance with coverage of not less than two million dollars ($2,000,000) per claim during the Term.

13. GOVERNING LAW AND VENUE

13.1 This Agreement is governed by the laws of the State of Florida, without regard to its conflict-of-laws rules. The state and federal courts located in Miami-Dade County, Florida have exclusive jurisdiction over any dispute arising out of this Agreement, and each party consents to personal jurisdiction there.

14. GENERAL

14.1 Assignment. Neither party may assign this Agreement without the other party's prior written consent, not to be unreasonably withheld, except that either party may assign this Agreement without consent to a successor in a merger, acquisition or sale of all or substantially all of its assets.

14.2 Force Majeure. Neither party is liable for any delay or failure to perform (other than payment obligations) caused by events beyond its reasonable control, including natural disasters, war, labor disputes, or failures of public utilities or the internet.

14.3 Notices. Notices must be in writing and delivered by hand, courier or email with confirmation of receipt to the addresses in the Order Form. Notices of non-renewal and termination are effective on receipt.

14.4 Publicity. Provider may identify Customer as a customer in its marketing materials, using Customer's name and logo.

14.5 Survival. Sections 3, 6, 7, 10, 11 and 13 survive termination or expiration of this Agreement.

14.6 Entire Agreement. This Agreement, together with each Order Form, is the entire agreement between the parties about its subject matter and supersedes all prior proposals and agreements. It may be amended only in a writing signed by both parties.

14.7 Independent Contractors. The parties are independent contractors. Nothing in this Agreement creates a partnership, joint venture or agency relationship.

14.8 Severability; Waiver. If any provision is held unenforceable, the remainder stays in effect. A failure to enforce a provision is not a waiver.

IN WITNESS WHEREOF, the parties have executed this Agreement as of the Effective Date.

STRATUS LEDGER SYSTEMS, LLC                      CASCADE OUTDOOR SUPPLY, INC.
By: ______________________                        By: ______________________
Name/Title: ______________                        Name/Title: ______________
"""


INCOMING_NDA = """\nCONFIDENTIALITY AGREEMENT

This Confidentiality Agreement (the "Agreement") is made as of November 2, 2026 (the "Effective Date") by and between Northwind Retail Group, Inc., a Delaware corporation ("Company"), and Brightpath Labs, Inc., a Washington corporation ("Recipient").

1. Purpose. Company wishes to disclose certain information to Recipient so that Recipient can evaluate and propose a pilot integration of Recipient's demand-forecasting software with Company's store systems (the "Purpose").

2. Confidential Information. "Confidential Information" means any and all information disclosed by or on behalf of Company to Recipient, whether before or after the Effective Date, in any form or medium, whether or not marked or identified as confidential, including business plans, sales data, supplier terms, technical specifications, store layouts and personnel information.

3. Exclusions. Confidential Information does not include information that Recipient can demonstrate by written records (a) is or becomes publicly available through no act or omission of Recipient; (b) was rightfully in Recipient's possession without restriction before receipt from Company; or (c) is received by Recipient from a third party that is not under an obligation of confidentiality to Company.

4. Obligations. Recipient shall (a) use Confidential Information solely for the Purpose; (b) not disclose Confidential Information to anyone other than its employees and professional advisers who have a need to know it for the Purpose and are bound by written obligations of confidentiality at least as protective as this Agreement; and (c) protect Confidential Information with at least the same degree of care it uses for its own confidential information, and no less than reasonable care. Recipient is responsible for any breach by its employees and advisers.

5. Compelled Disclosure. If Recipient is required by law, regulation or court order to disclose Confidential Information, Recipient shall give Company prompt written notice so that Company may seek a protective order, and shall disclose only the portion that it is legally required to disclose.

6. Term. This Agreement and Recipient's obligations under it shall remain in effect for a period of ten (10) years from the Effective Date.

7. Non-Solicitation. During the term of the parties' discussions and for twenty-four (24) months after they end, Recipient shall not, directly or indirectly, solicit or hire any employee of Company or solicit any customer or supplier of Company with whom Recipient had contact in connection with the Purpose.

8. Return of Materials. Within thirty (30) days after Company's written request, Recipient shall return or destroy all Confidential Information in its possession and, on request, certify the destruction in writing, except that Recipient may keep one archival copy for legal compliance purposes.

9. Ownership; Improvements. All Confidential Information remains the property of Company. Recipient hereby assigns to Company all right, title and interest in any suggestions, improvements, modifications or derivative works that Recipient creates based on or relating to the Confidential Information.

10. Remedies. Recipient agrees that any breach of this Agreement may cause Company irreparable harm, and that Company shall be entitled to injunctive relief without posting a bond, in addition to any other remedies. Recipient shall reimburse Company for all attorneys' fees and costs incurred in enforcing this Agreement.

11. Governing Law. This Agreement is governed by the laws of the State of Delaware. The state and federal courts located in Wilmington, Delaware shall have exclusive jurisdiction over any dispute arising from this Agreement.

12. Miscellaneous. This Agreement is the entire agreement between the parties about its subject matter. It may be amended only in a writing signed by both parties. Recipient may not assign this Agreement without Company's prior written consent. No failure to exercise any right is a waiver.

NORTHWIND RETAIL GROUP, INC.            BRIGHTPATH LABS, INC.
By: ___________________                 By: ___________________
"""


DESIGNER_SOW = """\nINDEPENDENT CONTRACTOR AGREEMENT AND STATEMENT OF WORK

This Agreement is between Fernhill Coffee Roasters LLC ("Client") and Maya Ortiz, doing business as Ortiz Studio ("Designer"), effective January 5, 2027.

1. Services. Designer will create a new brand identity for Client, including a logo, color palette, typography, packaging designs for Client's coffee bags, and related marketing materials as needed, etc. Designer will provide ongoing support for brand questions after launch.

2. Revisions and Approval. Designer will provide unlimited revisions until Client is satisfied. Work is complete when it is approved to Client's complete satisfaction.

3. Schedule. Designer will deliver initial logo concepts by February 1, 2027 and final files by March 15, 2027. Time is of the essence.

4. Fees and Payment. Client will pay Designer a fixed fee of $9,600 for the Services. Designer will invoice the full fee on completion of the Services, and Client will pay within sixty (60) days of receiving the invoice.

5. Ownership. All work product, including concepts, sketches and drafts, created by Designer under this Agreement is a work made for hire and is the sole property of Client from the moment of creation.

6. Termination. Client may terminate this Agreement at any time, for any reason, upon written notice to Designer.

7. Independent Contractor. Designer is an independent contractor, not an employee, and is responsible for her own taxes, equipment and insurance.

8. Confidentiality. Designer will keep Client's non-public business information confidential and will not disclose it to third parties.

9. Governing Law. This Agreement is governed by the laws of the State of Oregon, and the courts of Multnomah County, Oregon have exclusive jurisdiction.

Signed:
Fernhill Coffee Roasters LLC ____________    Maya Ortiz ____________
"""


HABITLOOP_POLICY = """\nHabitloop Privacy Policy
Effective date: 2026-10-01

1. Who we are and how to contact us
Habitloop, Inc. ("Habitloop", "we") runs the Habitloop habit-tracking app and website. We are a Delaware company based in Denver, Colorado, USA. We are the controller of your personal data. Contact us at privacy@habitloop.app or Habitloop, Inc., 1550 Wynkoop St, Denver, CO 80202, USA. Our EU representative under Article 27 GDPR is [EU REPRESENTATIVE NAME AND ADDRESS].

2. What we collect and where it comes from
We collect information directly from you, automatically from your device, and from our payment processor.
- From you: your name, email address and password (stored as a hash); messages you send to our support team.
- Automatically: IP address, browser and device type, and product usage events (features used, clicks, sessions), collected through cookies and similar tools.
- From Stripe: card brand, last 4 digits, billing country and transaction history. Stripe handles your full card number; we never see or store it.
You must give us your email address and a password to create an account. If you do not provide them, we cannot give you an account. Everything else is optional or collected automatically.

3. Why we use it and our legal bases
- To create and run your account, send service emails and take payments: performance of a contract with you.
- To keep the service secure and prevent fraud: our legitimate interests in protecting our users and systems.
- To measure how the app is used and improve it: your consent, which you give through our cookie banner. You can withdraw consent at any time in Cookie Settings.
- To send our product newsletter: your consent. Every newsletter has an unsubscribe link.
- To keep tax and accounting records: legal obligation.
We do not make decisions about you based solely on automated processing, and we do not profile you.

4. Who we share it with
We share personal data only with these service providers, who process it on our instructions:
- Amazon Web Services (hosting, USA)
- Postmark (email delivery, USA)
- Stripe (payments, USA)
- Mixpanel and Google Analytics (product analytics, USA), only if you accept analytics cookies
- Help Scout (support inbox, USA)
We may also disclose data to authorities when the law requires it. We do not sell your personal information and we do not share it for cross-context behavioral advertising.

5. International transfers
We are based in the United States, so your data is processed in the US. When we transfer data from the EU/EEA, we rely on the EU-U.S. Data Privacy Framework where the recipient is certified, and on Standard Contractual Clauses otherwise. You can ask us for a copy of the safeguards.

6. How long we keep it
- Account data (name, email, password hash): while your account is open, then deleted within 30 days of closing it.
- Server logs with IP address: 90 days.
- Product analytics events: 14 months.
- Support messages: 3 years after the conversation ends.
- Billing and transaction records: 7 years, because tax law requires it.

7. Your rights and how to exercise them
If you are in the EU/EEA, you have the right to access, rectify, erase, restrict and object to processing of your personal data, and to data portability. Where we rely on consent, you can withdraw it at any time. You can update your name and email in Account Settings. To exercise any right, email privacy@habitloop.app. We will answer within one month. You also have the right to lodge a complaint with your local data protection authority.

8. Cookies and tracking
We use strictly necessary cookies to keep you logged in. With your consent we use analytics cookies from Google Analytics and Mixpanel. You can change your choice at any time in Cookie Settings. Our site does not respond to browser Do Not Track signals, because there is no common standard for them; instead we honor your cookie choices. We do not allow third parties to collect personal information about your activity across other websites over time through our service.

9. Children
Habitloop is not for children under 16. We do not knowingly collect personal data from children under 16. If you believe a child has given us data, contact us and we will delete it.

10. Security
We encrypt data in transit and at rest, limit staff access to what they need, and hash passwords.

11. Changes to this policy
If we make a material change, we will email you and show a notice in the app at least 14 days before it takes effect. The effective date at the top shows the latest version.

12. California residents
We collect the categories of information described in section 2 and share them only with the service providers in section 4. You can review and update your account information in Account Settings, or email us to request changes.
"""


# ═══ 1. Contract Reviewer — customer reviewing a vendor SaaS agreement ═════════════════

FAIR_SUBS = [
    ("3.2 Provider may change the Fees, or introduce new fees for existing features, at any time upon written notice to Customer, and the revised Fees shall apply from the date stated in the notice. Customer's continued use of the Services after that date constitutes acceptance of the revised Fees.",
     "3.2 Fees are fixed for the Initial Term. Provider may increase the Fees for a Renewal Term by no more than 5% by giving written notice at least sixty (60) days before the renewal date."),
    ("at least ninety (90) days prior to the end", "at least thirty (30) days prior to the end"),
    ("5.1 Provider may terminate this Agreement for convenience at any time upon thirty (30) days' written notice to Customer.",
     "5.1 Either party may terminate this Agreement for convenience upon ninety (90) days' written notice; if Provider does so, it will refund prepaid Fees for the remainder of the term."),
    ("5.3 Fees paid or payable for the Initial Term or any Renewal Term are non-cancellable and non-refundable, and Customer shall have no right to terminate this Agreement prior to the end of the then-current term except as set out in Section 5.2.",
     "5.3 On termination, Customer pays Fees accrued through the termination date."),
    ("6.1 Customer grants Provider a worldwide, perpetual, irrevocable, royalty-free license to use, copy, modify and create derivative works of Customer Data and Usage Data to provide, maintain and improve the Services and Provider's other products and services.",
     "6.1 As between the parties, Customer owns all right, title and interest in Customer Data. Customer grants Provider a non-exclusive license during the Term to use Customer Data solely to provide the Services."),
    ("6.2 Provider owns all right, title and interest in and to the Services, Usage Data, and all aggregated or de-identified data derived from Customer Data, and all improvements to any of them.",
     "6.2 Provider owns the Services and Usage Data. Provider may compile aggregated statistics that do not identify Customer or any individual."),
    (" Customer's obligations under this Section 10.1 are not subject to any limitation of liability in this Agreement.", ""),
    ("10.1 Customer shall defend, indemnify and hold harmless Provider and its affiliates, officers and employees from and against any and all claims, losses, damages, liabilities, costs and expenses (including attorneys' fees) arising out of or relating to Customer Data, Customer's use of the Services, or any breach of this Agreement by Customer or its Users.",
     "10.1 Provider shall defend, indemnify and hold harmless Customer from any third-party claim that the Services infringe intellectual property rights. Customer shall defend, indemnify and hold harmless Provider from any third-party claim arising from Customer Data uploaded in violation of law."),
    ("11.2 PROVIDER'S AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT SHALL NOT EXCEED THE FEES PAID BY CUSTOMER IN THE ONE (1) MONTH PRECEDING THE EVENT GIVING RISE TO THE CLAIM.",
     "11.2 EACH PARTY'S AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THIS AGREEMENT SHALL NOT EXCEED THE FEES PAID OR PAYABLE IN THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM."),
    ("the laws of the State of Florida", "the laws of the State of Oregon"),
    ("Miami-Dade County, Florida", "Multnomah County, Oregon"),
]

# planted issue -> the flag text that proves the tool caught it
CONTRACT_PLANTED = {
    "auto-renewal with 90-day notice": "notice period of 90+ days",
    "uncapped indemnity from customer": "carved out of the cap",
    "liability cap = 1 month of fees": "liability cap = 1 month(s) of fees",
    "unilateral price changes": "unilateral right to change fees",
    "one-sided termination": "only the vendor may terminate for convenience",
    "far-away governing law / venue": "not your home jurisdiction (Oregon)",
    "data ownership ambiguity": "ownership of Customer Data is ambiguous",
}


def fair_contract() -> str:
    text = SAAS_CONTRACT
    for old, new in FAIR_SUBS:
        assert old in text, old[:60]
        text = text.replace(old, new)
    return text


def test_contract_review_catches_all_seven_planted_issues():
    out = call("contract-reviewer", "detect_clauses", contract_text=SAAS_CONTRACT, my_role="customer", my_jurisdiction="Oregon")
    flags = " | ".join(flags_of(out))
    missed = [issue for issue, proof in CONTRACT_PLANTED.items() if proof not in flags]
    assert missed == [], f"planted issues missed: {missed}"
    assert "perpetual, irrevocable licence to your data" in flags  # the data problem is also quoted
    assert out["liability_cap"]["capped_party"] == "vendor" and out["liability_cap"]["months_of_fees"] == 1
    assert out["governing_law"] == "Florida" and "Miami-Dade" in out["venue"]
    assert out["risk_score"] >= 50 and out["verdict"].startswith("Do not sign")
    # regressions: "limited liability company" is not a liability cap; "revenues" is not a venue clause
    clauses = {c["key"]: c["excerpt"] for c in out["clauses_found"]}
    assert "limited liability company" not in clauses["limitation_of_liability"]
    assert "Florida" in clauses["governing_law"] or "governed by" in clauses["governing_law"]


def test_contract_review_precision_on_market_standard_version():
    out = call("contract-reviewer", "detect_clauses", contract_text=fair_contract(), my_role="customer", my_jurisdiction="Oregon")
    serious = [f["flag"] for f in out["red_flags"] if f["severity"] >= 2]
    assert serious == [], f"false alarms on market-standard terms: {serious}"
    assert out["risk_score"] < 25 and out["verdict"].startswith("Routine")
    assert out["liability_cap"] == {**out["liability_cap"], "capped_party": "both", "mutual": True, "months_of_fees": 12}


def test_contract_dates_match_hand_calculation():
    eff = date(2026, 10, 31)
    end = last_day_of_term(eff, 12)
    notice = end - timedelta(days=90)
    assert (end, notice) == (date(2027, 10, 30), date(2027, 8, 1)) and notice.weekday() == 6  # a Sunday
    dl = call("contract-reviewer", "extract_deadlines", contract_text=SAAS_CONTRACT, effective_date="2026-10-31")
    assert dl["initial_term_ends"] == end.isoformat()
    ninety = next(d for d in dl["durations"] if d["days"] == 90)
    assert ninety["counts_from"] == "before end of term" and ninety["from_effective_date"] is None
    assert ninety["deadline_in_initial_term"] == notice.isoformat()
    survival = next(d for d in dl["durations"] if d["duration"] == "3 years")
    assert survival["type"] == "confidentiality / survival"  # not a 1,095-day "notice period"
    assert dl["longest_notice_days"] == 90
    for d in dl["durations"]:  # event-anchored durations are never shown as effective-date dates
        if d["counts_from"] in ("from notice", "from invoice date", "after termination / expiry"):
            assert d["from_effective_date"] is None
    cal = call("contract-reviewer", "renewal_calendar", effective_date="2026-10-31", initial_term_months=12, notice_days=90)
    assert cal["initial_term_end"].startswith("2027-10-30") and cal["notice_deadline"].startswith("2027-08-01")
    assert cal["reminder_date"].startswith((notice - timedelta(days=30)).isoformat())
    assert friday_before(notice).isoformat() in cal["weekend_note"]  # 2027-07-30
    r1 = cal["renewal_cycles"][0]
    assert (r1["starts"], r1["ends"], r1["notice_deadline"]) == ("2027-10-31", last_day_of_term(date(2027, 10, 31), 12).isoformat(), "2028-08-01")


def test_contract_liability_math():
    out = call("contract-reviewer", "liability_exposure", annual_contract_value=48_000, cap_type="months_of_fees", cap_value=1, mutual=False)
    assert out["cap_dollars"] == 48_000 * 1 / 12 == 4_000 and out["market_reference_cap"] == 48_000
    assert "below market" in out["market_position"] and out["cap_description"] == "1 month of fees"
    assert any("not mutual" in f for f in out["findings"]) and "entire liability" in out["uncapped_exposure"]


# ═══ 2. Privacy Policy — US startup, EU + California users, email/analytics/payments ═════

INVENTORY = [
    {"data": "email address", "purpose": "account login, transactional emails, product newsletter (opt-in marketing)", "shared_with": "AWS, Postmark", "retention": "life of account + 30 days"},
    {"data": "name", "purpose": "account, customer support", "shared_with": "AWS", "retention": "life of account + 30 days"},
    {"data": "password (hashed)", "purpose": "account login authentication", "shared_with": "AWS", "retention": "life of account"},
    {"data": "IP address and browser/device information", "purpose": "security, fraud prevention, analytics", "shared_with": "AWS, Google Analytics", "retention": "90 days in logs"},
    {"data": "product usage events (features used, clicks, sessions)", "purpose": "product analytics to improve the service", "shared_with": "Mixpanel, Google Analytics", "retention": "14 months"},
    {"data": "analytics cookies (_ga, Mixpanel)", "purpose": "analytics", "shared_with": "Google, Mixpanel", "retention": "up to 13 months"},
    {"data": "payment details: card processed by Stripe; we keep card brand, last 4 digits, billing country, transaction history", "purpose": "billing, subscription payments, tax records", "shared_with": "Stripe", "retention": "7 years for tax records"},
    {"data": "support messages sent to us", "purpose": "customer support", "shared_with": "Help Scout", "retention": "3 years"},
]
CCPA_REVENUE_THRESHOLD_2025 = 26_625_000  # privacy.ca.gov monetary thresholds, effective 2025-01-01


def test_privacy_applicability_matches_the_statutes():
    base = dict(company_country="US", annual_revenue_usd=1_800_000, sells_or_shares_data=False)
    assert base["annual_revenue_usd"] < CCPA_REVENUE_THRESHOLD_2025
    out = call("privacy-policy", "check_applicability", user_regions=["California", "Germany", "France", "EU"], consumers_per_year=42_000, **base)
    names = out["regime_names"]
    assert "GDPR (EU/EEA)" in names and "CalOPPA (California)" in names  # Art. 3(2); B&P §22575 has no threshold
    assert "US state privacy laws" not in names and not any("PIPEDA" in n for n in names)  # 'california' is not Canada
    # 150k Californians collected but never bought/sold/shared: 1798.140(d)(1)(B) is not met
    big = call("privacy-policy", "check_applicability", user_regions=["California", "EU"], consumers_per_year=150_000, **base)
    assert "US state privacy laws" not in big["regime_names"] and any("1798.140(d)(1)(B)" in n for n in big["not_triggered_notes"])
    shared = call("privacy-policy", "check_applicability", user_regions=["California", "EU"], consumers_per_year=150_000, **{**base, "sells_or_shares_data": True})
    assert "US state privacy laws" in shared["regime_names"]
    austria = call("privacy-policy", "check_applicability", company_country="US", user_regions=["Austria"])
    assert austria["regime_names"] == ["GDPR (EU/EEA)"]  # not US ('us' in austria) or Australia ('au')


def test_privacy_inventory_classification():
    out = call("privacy-policy", "classify_data_inventory", data_items=INVENTORY)
    items = {i["data"].split(" ")[0]: i for i in out["items"]}
    assert "contact" not in items["IP"]["categories"]  # "IP address" is not a postal address
    assert "identity" not in items["product"]["categories"]  # "usage" does not contain the word "age"
    assert items["payment"]["cpra_sensitive"] is False  # last-4 + brand is not a card number with access code
    assert items["support"]["cpra_sensitive"] is False  # the business is the intended recipient
    assert items["password"]["cpra_sensitive"] is True  # account log-in + password is SPI (1798.140(ae))
    assert any("ePrivacy" in f for f in items["analytics"]["flags"])  # EU cookie consent
    assert out["special_category_data"] == [] and out["sale_or_share_candidates"] == []


def test_privacy_policy_audit_and_lint():
    regimes = ["GDPR (EU/EEA)", "CalOPPA (California)", "US — below state thresholds (verify)"]
    full = call("privacy-policy", "required_sections", regimes=regimes, policy_text=HABITLOOP_POLICY)
    assert full["regimes_applied"] == ["CALOPPA", "GDPR"] and full["unknown_regimes"] == []
    assert full["coverage_pct"] == 100 and full["missing"] == []
    gutted = HABITLOOP_POLICY.split("5. International transfers")[0] + "6. How long we keep it" + HABITLOOP_POLICY.split("6. How long we keep it")[1]
    gutted = gutted.replace("Our site does not respond to browser Do Not Track signals, because there is no common standard for them; instead we honor your cookie choices. ", "")
    audit = call("privacy-policy", "required_sections", regimes=regimes, policy_text=gutted)
    assert {m["section"] for m in audit["missing"]} == {"transfers", "dnt"}
    lint = call("privacy-policy", "lint_policy_text", policy_text=HABITLOOP_POLICY)
    assert lint["readability"]["passes"] and lint["score"] >= 85 and lint["missing_basics"] == []


# ═══ 3. NDA Drafter — incoming one-way NDA, we are the recipient ══════════════════════

NDA_PLANTED = {
    "10-year term": "Term length",
    "non-solicit": "Non-solicitation in an NDA",
    "missing independent-development exclusion": "Exclusion: independently developed",
    "IP assignment of improvements": "IP assignment / ownership of improvements inside an NDA",
    "one-way attorneys' fees": "One-way attorneys' fees",
    "all information, marked or not": "Confidential Information defined as all information without limit",
}


def test_nda_review_recall_and_precision():
    out = call("nda-drafter", "review_nda", nda_text=INCOMING_NDA, my_role="recipient")
    clauses = [f["clause"] for f in out["findings"]]
    missed = [k for k, v in NDA_PLANTED.items() if v not in clauses]
    assert missed == [], f"planted issues missed: {missed}"
    assert len(clauses) == len(NDA_PLANTED), f"false alarms: {set(clauses) - set(NDA_PLANTED.values())}"
    assert out["term_note"] == "term/survival language found: 10 years"  # not the 24-month non-solicit
    assert next(f for f in out["findings"] if f["clause"] == "Term length")["severity"] == 2
    assert out["verdict"] == "Do not sign as-is"


def test_nda_dates_and_counter_draft():
    eff = date(2026, 11, 2)
    as_written = call("nda-drafter", "calculate_terms", effective_date="2026-11-02", term_months=120, survival_months=0, early_termination_allowed=False)
    assert as_written["term_end"].startswith(last_day_of_term(eff, 120).isoformat())  # 2036-11-01
    assert as_written["earliest_early_termination"].startswith("no early-termination right")
    counter = call("nda-drafter", "calculate_terms", effective_date="2026-11-02", term_months=24, survival_months=36)
    term_end = last_day_of_term(eff, 24)
    assert counter["term_end"].startswith(term_end.isoformat())
    assert counter["obligations_end_ordinary_information"].startswith(last_day_of_term(term_end + timedelta(days=1), 36).isoformat())  # 2031-11-01
    draft = call("nda-drafter", "build_nda", party_a={"name": "Northwind Retail Group, Inc."}, party_b={"name": "Brightpath Labs, Inc."},
                 purpose="evaluating a pilot integration", effective_date="2026-11-02", governing_law="the State of Delaware")
    for role in ("both", "recipient", "discloser"):  # our own draft must pass our own review
        assert call("nda-drafter", "review_nda", nda_text=draft["agreement_text"], my_role=role)["findings"] == []


# ═══ 4. Grant Writer — $250k, 2-year federal award, nonprofit on the de minimis rate ════

GRANT_LINES = [
    {"category": "personnel", "description": "Program Director", "salary": 70000, "fte": 0.25, "months": 24},
    {"category": "personnel", "description": "Program Coordinator", "salary": 52000, "fte": 0.5, "months": 24},
    {"category": "travel", "description": "Site visits and conference", "quantity": 6, "unit_cost": 1200},
    {"category": "equipment", "description": "Mobile STEM lab trailer", "quantity": 1, "unit_cost": 18000},
    {"category": "equipment", "description": "Laptops for participants", "quantity": 4, "unit_cost": 1800},
    {"category": "supplies", "description": "Curriculum materials", "amount": 6500},
    {"category": "participant_support", "description": "Participant stipends", "quantity": 40, "unit_cost": 250},
    {"category": "evaluation", "description": "External evaluator (contract)", "amount": 15000},
    {"category": "subaward", "description": "State University partner - Year 1", "subrecipient": "State University", "amount": 40000},
    {"category": "subaward", "description": "State University partner - Year 2", "subrecipient": "State University", "amount": 20000},
]


def reference_mtdc(subaward_allowance: float) -> tuple[float, float]:
    """Hand MTDC per 2 CFR 200.1: salaries + fringe + travel + supplies (incl. sub-threshold laptops) + services + first $X of the subaward."""
    salaries = 70000 * 0.25 * 2 + 52000 * 0.5 * 2
    fringe = salaries * 0.30
    direct = salaries + fringe + 6 * 1200 + 18000 + 4 * 1800 + 6500 + 40 * 250 + 15000 + 60000
    mtdc = salaries + fringe + 6 * 1200 + 4 * 1800 + 6500 + 15000 + min(60000, subaward_allowance)
    return direct, mtdc


def test_grant_budget_mtdc_2024_rules():
    direct, mtdc = reference_mtdc(50_000)
    out = call("grant-writer", "budget_table", line_items=GRANT_LINES, fringe_rate_pct=30, indirect_rate_pct=15, indirect_base="mtdc", request_cap=250_000)
    assert (out["total_direct"], out["mtdc"]) == (direct, mtdc) == (237_000, 199_000)
    assert out["indirect"] == mtdc * 0.15 == 29_850 and out["total_request"] == 266_850
    assert out["mtdc_exclusions"] == {"equipment": 18_000, "participant_support": 10_000, "subaward amounts above $50,000 each": 10_000}
    assert any("Laptops" in f and "supplies" in f for f in out["flags"])  # $1,800/unit < $10,000
    over = next(f for f in out["flags"] if "exceeds the $250,000 cap" in f)
    assert f"${(266_850 - 250_000) / 1.15:,.0f}" in over  # $14,652 of MTDC-eligible cuts, not $16,850


def test_grant_budget_pre_2024_award_and_revision_under_cap():
    direct, mtdc = reference_mtdc(25_000)
    old = call("grant-writer", "budget_table", line_items=GRANT_LINES, fringe_rate_pct=30, indirect_rate_pct=10, indirect_base="mtdc", uniform_guidance="pre-2024")
    assert old["mtdc"] == mtdc == 174_000 and old["indirect"] == 17_400
    revised_lines = [dict(li) for li in GRANT_LINES]
    revised_lines[1]["fte"] = 0.4
    revised_lines[2]["quantity"] = 5
    rev = call("grant-writer", "budget_table", line_items=revised_lines, fringe_rate_pct=30, indirect_rate_pct=15, indirect_base="mtdc", request_cap=250_000)
    salaries = 70000 * 0.25 * 2 + 52000 * 0.4 * 2
    hand_mtdc = salaries * 1.3 + 5 * 1200 + 4 * 1800 + 6500 + 15000 + 50000
    hand_total = salaries * 1.3 + 5 * 1200 + 18000 + 4 * 1800 + 6500 + 10000 + 15000 + 60000 + hand_mtdc * 0.15
    assert rev["total_request"] == round(hand_total, 2) == 249_922 and not any("cap" in f for f in rev["flags"])


def test_grant_timeline_federal_reporting():
    out = call("grant-writer", "project_timeline", start_date="2027-01-01", duration_months=24, reporting="semiannual", federal_award=True,
               milestones=[{"name": "Cohort 1 begins", "month": 4}, {"name": "Evaluation report", "month": 25}])
    end = last_day_of_term(date(2027, 1, 1), 24)
    assert out["period_of_performance"]["end"] == end.isoformat() == "2028-12-31"
    assert out["reports"][-1]["due"] == (end + timedelta(days=120)).isoformat() == "2029-04-30"  # 2 CFR 200.344(b)
    assert [r["due"] for r in out["reports"][:-1]] == ["2027-07-30", "2028-01-30", "2028-07-30"]
    assert out["milestones_outside_period"] == ["Evaluation report"]


def test_grant_criteria_coverage_finds_the_thin_evaluation_plan():
    sections = [
        {"name": "Need", "criterion": "Need", "text": "Rural middle schools in Lane County offer no after-school computing. In 2025, 3 of 11 schools had a computer science elective. Girls made up 22% of enrolled students. The nearest coding club is a 45-minute drive."},
        {"name": "Approach", "criterion": "Approach", "text": "We will run two 16-week after-school cohorts per year at four rural middle schools, serving 120 students over two years. A mobile STEM lab brings laptops, robotics kits and a trained coordinator to each school twice a week. State University faculty co-design the curriculum and train 8 teachers per year. Recruitment targets 50% girls through counselors and a parent night at each site. Participants receive a stipend for completing a capstone project."},
        {"name": "Evaluation", "criterion": "Evaluation", "text": "An external evaluator will measure attendance and pre/post assessment scores."},
    ]
    criteria = [{"name": "Need", "weight": 20}, {"name": "Approach", "weight": 40}, {"name": "Evaluation", "weight": 40}]
    objectives = ["By 2028-12-31, 120 rural middle-school students will complete at least 24 hours of computing instruction, as measured by attendance records.", "Empower young people to love technology."]
    out = call("grant-writer", "criteria_coverage", sections=sections, criteria=criteria, objectives=objectives)
    ev = next(c for c in out["criteria"] if c["criterion"] == "Evaluation")
    assert ev["status"] == "under-covered vs weight"
    assert [o["score"] for o in out["objectives"]] == [4, 0]  # "technology" no longer counts as a measurement "log"


# ═══ 5. Freelance Contract — designer reviewing a client SOW with "unlimited revisions" ══

SOW_PLANTED_SCOPE = {"unlimited revisions", "subjective acceptance standard", "open-ended scope language", "exclusions", "revision cap", "change order"}
SOW_PLANTED_TRAPS = {"Work-for-hire / assignment not conditioned on payment", "Unlimited revisions / subjective acceptance", "Payment terms of net 60 or longer", "Client can terminate at any time with no payment for work done"}


def test_freelance_scope_and_clause_audit():
    scope = call("freelance-contract", "scope_creep_check", sow_text=DESIGNER_SOW)
    issues = {f["issue"] for f in scope["findings"]}
    assert SOW_PLANTED_SCOPE <= issues and scope["verdict"].startswith("Scope-creep magnet")
    audit = call("freelance-contract", "check_contract_clauses", contract_text=DESIGNER_SOW, my_role="freelancer")
    traps = {t["flag"] for t in audit["traps"]}
    assert traps == SOW_PLANTED_TRAPS  # and no non-compete false alarm from "exclusive jurisdiction"
    missing = {m["clause"] for m in audit["missing"]}
    assert {"Deposit / upfront payment", "Kill fee / early termination payment", "IP transfers only on full payment", "Change orders"} <= missing
    assert "Payment terms (net days)" not in missing  # "within sixty (60) days of receiving the invoice" is a payment term


def test_freelance_schedule_and_rate_math():
    fee = 9600
    out = call("freelance-contract", "milestone_schedule", total_fee=fee, start_date="2027-01-05", deposit_pct=40, payment_terms_days=15,
               milestones=[{"name": "Logo concepts", "pct": 30, "date": "2027-02-01", "deliverable": "3 logo concepts"},
                           {"name": "Final files", "pct": 30, "date": "2027-03-15", "deliverable": "final logo suite and 2 bag designs"}])
    rows = out["schedule"]
    assert [r["amount"] for r in rows] == [fee * 0.4, fee * 0.3, fee * 0.3]
    assert [r["due_date"] for r in rows] == ["2027-01-05", (date(2027, 2, 1) + timedelta(days=15)).isoformat(), (date(2027, 3, 15) + timedelta(days=15)).isoformat()]
    assert rows[0]["kill_fee_if_cancelled_after_this"] == fee * 0.6 * 0.25 and out["flags"] == []
    rate = call("freelance-contract", "rate_calculator", target_income=85000, billable_hours_per_week=25, weeks_off=6, annual_overhead=8000, fixed_fee=9600, estimated_hours=80)
    hand = (85000 * (1 + 0.153 + 0.10) + 8000) * 1.10 / ((52 - 6) * 25)
    assert rate["minimum_hourly"] == round(hand, 2) and rate["hourly_rate_rounded"] == 110
    assert rate["fixed_fee_check"]["effective_hourly_rate"] == 9600 / (80 * 1.2) and rate["fixed_fee_check"]["recommended_fixed_fee"] == 10560
